rust: do not use dummy linker for rust
Otherwise you will get:

    error: failed to run custom build command for `serde v1.0.219`

    Caused by:
      could not execute process `/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/ci/tmp/build/./cargo/build/chdig_cca6e/debug/build/serde-ada0f1f32dbba4cb/build-script-build` (never executed)

    Caused by:
      Permission denied (os error 13)
    warning: build failed, waiting for other jobs to finish...

CI: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=79666&sha=f7b62e1a8e532d49c54c753d8b02ca93547de4c5&name_0=PR&name_1=Build%20%28amd_tidy%29