Use overload over default value for IStorage::getQueryProcessingStage()
Since clang-tidy complains about it [1]:

    2020-03-24 09:00:53 /build/obj-x86_64-linux-gnu/../dbms/src/Storages/StorageMerge.cpp:139:42: error: default arguments on virtual or override methods are prohibited [google-default-arguments,-warnings-as-errors]
    2020-03-24 09:00:53 QueryProcessingStage::Enum StorageMerge::getQueryProcessingStage(const Context & context, const ASTPtr & query_ptr) const

  [1]: https://clickhouse-builds.s3.yandex.net/9808/52c639c286afef7b418f87787a11637388547b08/build_log_637307151_1585043194.txt

And indeed, this is a good idea!