tests: fix fata/sanitizers log unlink
By some reason it does not complains with 3.13, but complains with 3.10:

    1 tests passed. 0 tests skipped. 0.95 s elapsed (Process-3).
    Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x71a44a9ef370>
    Traceback (most recent call last):
      File "/usr/lib/python3.10/tempfile.py", line 605, in __del__
        self.close()
      File "/usr/lib/python3.10/tempfile.py", line 601, in close
        unlink(self.name)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/clickhouse-private/tests/queries/0_stateless/test_77sylcp8/clickhouse-test-h_0jjik2.log'
    All tests have finished.

The reason is that rmtree(tmpdir) called before the NamedTemporaryFile
destructor.